### ISSUE TITLE
php artisan langman:show validation - Error strstr() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by rsdev000** [themsaid/laravel-langman#35]
Hi

Found this error while working in a 5.2.31 app and tested in a fresh 5.2.32.

The error only occurs when showing validation. It works ok with auth, passwords, pagination language files.

![ok-1](https://cloud.githubusercontent.com/assets/9252353/15326236/27415fe4-1c45-11e6-8bba-ef7e62704c50.png)

![err-1](https://cloud.githubusercontent.com/assets/9252353/15326247/2e4874c6-1c45-11e6-907e-976e5f75e5fe.png)

```php
[2016-05-17 14:20:43] local.ERROR: ErrorException: strstr() expects parameter 1 to be string, array given in C:\Work\www\projects\aa\vendor\symfony\console\Helper\Table.php:398
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'strstr() expect...', 'C:\\Work\\www\\pro...', 398, Array)
#1 C:\Work\www\projects\aa\vendor\symfony\console\Helper\Table.php(398): strstr(Array, '\n')
#2 C:\Work\www\projects\aa\vendor\symfony\console\Helper\Table.php(256): Symfony\Component\Console\Helper\Table->buildTableRows(Array)
#3 C:\Work\www\projects\aa\vendor\laravel\framework\src\Illuminate\Console\Command.php(339): Symfony\Component\Console\Helper\Table->render()
#4 C:\Work\www\projects\aa\vendor\themsaid\laravel-langman\src\Commands\ShowCommand.php(95): Illuminate\Console\Command->table(Array, Array)
#5 [internal function]: Themsaid\Langman\Commands\ShowCommand->handle()
#6 C:\Work\www\projects\aa\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#7 C:\Work\www\projects\aa\vendor\laravel\framework\src\Illuminate\Console\Command.php(169): Illuminate\Container\Container->call(Array)
#8 C:\Work\www\projects\aa\vendor\symfony\console\Command\Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 C:\Work\www\projects\aa\vendor\laravel\framework\src\Illuminate\Console\Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 C:\Work\www\projects\aa\vendor\symfony\console\Application.php(791): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 C:\Work\www\projects\aa\vendor\symfony\console\Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Themsaid\Langman\Commands\ShowCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 C:\Work\www\projects\aa\vendor\symfony\console\Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 C:\Work\www\projects\aa\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 C:\Work\www\projects\aa\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 {main}  
``` 

Cheers

**Comment by themsaid** [comment]
Can you share your `validation.php file`? is it the one coming with laravel as it is, no changes?

**Comment by rsdev000** [comment]
Yes. It's the one coming with laravel without changes.

**Comment by themsaid** [comment]
This is now fixed.
